export const ELEMENTS = {
  nameInput: 'input[name="name"]',
  emailInput: 'input[name="email"]',
  cpfInput: 'input[name="cpf"]',
  cepInput: 'input[name="cep"]',
  buscarCepButton: 'input[value="Buscar CEP"]',
  addressNumberInput: 'input[name="addressNumber"]',
  addressDetailsInput: 'input[name="addressDetails"]',
  cuidarOption: '[alt="Cuidar"]',
  adestrarOption: '[alt="Adestrar"]',
  fileInput: 'input[type="file"]',
  submitButton: '.button-register',
  alertMessage: 'div.swal2-html-container',
  errorMessage: 'div.error-message',
};
